### ISSUE TITLE
Feature Request - Collections

### ISSUE THREAD

**Issue by Haltroy** [Haltroy/Korot#100]
**To-Do List**
 - [x] Allow user to create new collections, delete collections or import/export collections (as XML code.)
 - [x] Add translations for context menus.
 - [x] Add context menu events to collection manager.
 - [x] Allow user to add text/image/link to a collection.
 - [x] Make collections global for that process. Then save collection file to user files location. And finally, load from that location.

**Comment by Haltroy** [comment]
Links (inside of `LinkLabel`) are so annoying that I had to make a custom LinkLabel and add string named `Url` to store URLs. Every time when I tried to read an link it returned null even tho I asked it to print every link to console on click.
`Tag` is used for outer XML code for that item so cannot store the link there.
This pissed me off too badly.

**Comment by Haltroy** [comment]
Current system is not stable so I need to came with something better.

**Comment by Haltroy** [comment]
I came with something better and going to release a new pre-release today fixing some bugs.
