### ISSUE TITLE
Feature Request - Group Tabs

### ISSUE THREAD

**Issue by Haltroy** [Haltroy/Korot#102]
**Is your feature request related to a problem? Please describe.**
Users might get confused which tab was originated from who.

**Describe the solution you'd like**
Right-click menu showing color setting of that tab. This color change will not affect its main theme but just top title part.
Also, Korot now does not creates tab after its sender tab, it creates at the end of tabs.

**Additional context**
Add ability to change colors of each tab to EasyTabs then try adding this feature.

**To-Do List**
 - [x] Add ability to change `TitleBarTab` color.
 - [x] Add right-click menu for `TitleBarTab`.
 - [x] Use `Insert` rather than `Add` while creating new tab.
