### ISSUE TITLE
Release News - 0.7 [Laika]

### ISSUE THREAD

**Issue by Haltroy** [Haltroy/Korot#116]
## Origin of Code Name
`Laika` is the name of the first dog in space. **[**[`Wikipedia article`](https://en.wikipedia.org/wiki/Laika)**]**.

## Important
Extension & Theme & Language system is going to be completely different than previous. New updated items are going to be released to [`Haltroy Web Store`](https://haltroy.com/store/) when this update is finished and ready to launch. Also, documentations are already updated for this update.
Korot now stores profiles in a different directory.

    (User Documents)\Korot\Profiles\(Profile Name) => (User Documents)\Korot\(Profile Name)

### :white_check_mark: 0.7-pre1:
 - [x] Resolve #106 - Migrate everything to new XML-based system.
 - [x] Resolve #114 - Site Settings
### :white_check_mark: 0.7-pre2:
 - [x] Resolve #115 - New language System
 - [x] Resolve #117 - Import/Export Profiles
### :white_check_mark:  0.7:  [*`full`*]
 - [X] Fix bugs & improve code.
 - [x] Fix all issues attached to this milestone.
 - [x] Release packages.
 - [x] Update web store items.
 - [x] Update information in [`haltroy.com`](https://haltroy.com).
 - [x] Announce new update.
