### ISSUE TITLE
0.8.2 ToDo

### ISSUE THREAD

**Issue by Haltroy** [Haltroy/Korot#145]
- [x] Recolor Logo
 - [x] Change OverlayColor of each theme.
 - [x] Add ForeColor features to each theme.
 - [x] Do not show addresses like `korot://error`.
 - [x] Show Korot icon in privacy button if it's a `korot://` page.
 - [x] Set icon to Korot icon if it's a `korot://` page.
 - [x] Fix about page update status text.
 - [x] Test the new update system.
