### ISSUE TITLE
Update 0.5 - The Last To-Do List

### ISSUE THREAD

**Issue by Haltroy** [Haltroy/Korot#60]
I almost finished this milestone but it can contain problems so I'm going to pre-release versions for now. The final product will end up having same features so don't worry.
If you spot something bad, please consider creating an issue so I can help.

## When all the problems are spotted and fixed
 - [x] Pre-Release a final version with bugfixes. ([0.5-pre4](https://github.com/Haltroy/Korot/releases/tag/0.5.0.0-pre4))

## When final pre-release has no problem or spotted problems and fixed them
 - [X] Release a full pre-release version (on Patreon first.) ([0.5-pre5](https://github.com/Haltroy/Korot/releases/tag/0.5.0.0-pre5))
 - [x] Release a full version to public  (if no bugs are detected in 3 days.)

**Comment by Haltroy** [comment]
Korot's new version is now complete. I added the last features (that I found in my book as a note lol).
I completely forgot about those notes that I took so I spend my half of a day to add those features.
